#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse

script_update=2019.07.13
script_version=r10000

################################################################################################ Debug

usage_for_debug() {
    export local_packages=/etc/inexistence/00.Installation
    export s=$local_packages/package/flexget/install
    rm -f $s ; nano $s ; bash $s
    bash <(wget -qO- https://github.com/Aniverse/inexistence/raw/master/00.Installation/package/flexget/install)
}

################################################################################################ Get options

unset AppName AppNameLower Need_SourceCode pm_action \
      LogRootPath LogTimes DebLocation SCLocation LOCKLocation OutputLOG \
      user

function show_usage() { echo " Invalid option $1" ; exit 1 ; }

OPTS=$(getopt -o u:v:l:d -al user:,version:,debug,logbase:,system -- "$@")
[ ! $? = 0 ] && show_usage
eval set -- "$OPTS"

while [ -n "$1" ] ; do case "$1" in
    -v | --version      ) version="$2"  ; shift 2 ;;
    -u | --user         ) user="$2"     ; shift 2 ;;
         --logbase      ) LogTimes="$2" ; shift 2 ;;
         --system       ) unset user    ; shift   ;;
         --debug        ) debug=1       ; shift   ;;
    -- ) shift ; break ;;
esac ; done

################################################################################################ Set Variables

AppName=FlexGet
AppNameLower=flexget
Need_SourceCode=no
pm_action=install

if [[ -f /etc/inexistence/00.Installation/function ]]; then
    source /etc/inexistence/00.Installation/function
else
    wget -qO /tmp/function https://github.com/Aniverse/inexistence/raw/master/00.Installation/function
    source /tmp/function
fi

set_variables_log_location
[[ $debug == 1 ]] && debug_log_location

################################################################################################





function install_flexget() {

    echo >> $OutputLOG

    apt_install python python-dev python-pip
    python2 -m pip install --upgrade pip >> "$OutputLOG" 2>&1
    python2 -m pip install pathlib >> "$OutputLOG" 2>&1
    python2 -m pip install transmissionrpc deluge-client >> "$OutputLOG" 2>&1

    if [[ -z $user ]]; then
        python2 -m pip install flexget >> "$OutputLOG" 2>&1
    else
        su $user -c 'python2 -m pip install flexget --user' >> "$OutputLOG" 2>&1
        export PATH=/home/$user/.local/bin:$PATH
    fi

    status_lock=$AppNameLower
    echo "status_lock=$status_lock" > /tmp/Variables
    rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock 
    which flexget > /dev/null && touch /tmp/$status_lock.1.lock || touch /tmp/$status_lock.2.lock
    [[ -f /tmp/$status_lock.1.lock ]] && touch $LOCKLocation/$AppNameLower.lock
    echo >> $OutputLOG

}





echo -ne "Installing $AppName ..." | tee -a $OutputLOG
install_flexget & spinner $!
check_status $status_lock | tee -a $OutputLOG

[[ $debug == 1 ]] && which flexget
