#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse

script_update=2019.07.13
script_version=r10000

################################################################################################

if [[ -f /etc/inexistence/00.Installation/function ]]; then
    source /etc/inexistence/00.Installation/function
else
    wget -qO /tmp/function https://github.com/Aniverse/inexistence/raw/master/00.Installation/function
    source /tmp/function
fi

qbtnox_ver=$( qbittorrent-nox --version 2>&1 | awk '{print $2}' | sed "s/v//" )
NewQBT=no ; [[ $CODENAME == Jessie ]] && NewQBT=no
################################################################################################


function ask_qbittorrent_test() {

    while [[ -z $qb_version ]]; do
    
        echo -e "${green}01)${normal} qBittorrent ${cyan}3.3.11${normal}"
        echo -e "${green}02)${normal} qBittorrent ${cyan}3.3.16${normal}"
        echo -e "${green}03)${normal} qBittorrent ${cyan}4.0.4${normal}"
        echo -e "${green}04)${normal} qBittorrent ${cyan}4.1.3${normal}"
        echo -e "${green}05)${normal} qBittorrent ${cyan}4.1.6${normal}"
        [[ $NewQBT == yes ]] && 
        echo -e  "${blue}11)${normal} qBittorrent ${blue}4.2.0${normal}"
        echo -e  "${blue}30)${normal} $language_select_another_version"
        echo -e "${green}40)${normal} qBittorrent ${cyan}$QB_repo_ver${normal} from ${cyan}repo${normal}"
        [[ $DISTRO == Ubuntu ]] &&
        echo -e "${green}50)${normal} qBittorrent ${cyan}$QB_latest_ver${normal} from ${cyan}Stable PPA${normal}"
        echo -e   "${red}99)${normal} $lang_do_not_install qBittorrent"
    
        [[ $qb_installed == Yes ]] &&
        echo -e "${bailanse}${bold} ATTENTION ${normal} ${blue}${bold}$lang_yizhuang ${underline}qBittorrent ${qbtnox_ver}${normal}"
    
        read -ep "${bold}${yellow}$which_version_do_you_want${normal} (Default ${cyan}05${normal}): " version
    
        case $version in
            01 | 1) qb_version=3.3.11 ;;
            02 | 2) qb_version=3.3.16 ;;
            03 | 3) qb_version=4.0.4 ;;
            04 | 4) qb_version=4.1.3 ;;
            05 | 5) qb_version=4.1.6 ;;
            30) _input_version && qb_version="${input_version_num}"  ;;
            40) qb_version=repo ;;
            50) qb_version=ppa ;;
            99) qb_version=no ;;
            * | "") qb_version=4.1.6 ;;
        esac
    
    done
    
    drop_libtorrent8=no ; version_ge $qb_version 4.1.4 && drop_libtorrent8=yes
    
    if [[ $qb_version == no ]]; then
        echo "${baizise}qBittorrent will ${baihongse}not${baizise} be installed${normal}\n"
    elif [[ $qb_version == repo ]]; then
        echo "${bold}${baiqingse}qBittorrent $QB_repo_ver${normal} ${bold}$lang_will_be_installed from system repository${normal}\n"
    elif [[ $qb_version == PPA ]]; then
        echo "${bold}${baiqingse}qBittorrent $QB_latest_ver${normal} ${bold}$lang_will_be_installed from Stable PPA${normal}\n"
    else
        echo -e "${bold}${baiqingse}qBittorrent ${qb_version}${normal} ${bold}$lang_will_be_installed${normal}\n"
    fi

}

ask_qbittorrent_test
