#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse

script_update=2019.07.11
script_version=r10000

################################################################################################ Debug

usage_for_debug() {
    export local_packages=/etc/inexistence/00.Installation
    rm -f $local_packages/package/wine/uninstall ; nano $local_packages/package/wine/uninstall
}

################################################################################################ Get options

unset AppName AppNameLower Need_SourceCode pm_action \
      LogRootPath LogTimes DebLocation SCLocation LOCKLocation OutputLOG

function show_usage() { echo " Invalid option $1" ; exit 1 ; }

OPTS=$(getopt -al debug,logbase: -- "$@")
[ ! $? = 0 ] && show_usage
eval set -- "$OPTS"

while [ -n "$1" ] ; do case "$1" in
         --logbase      ) LogTimes="$2" ; shift 2 ;;
         --debug        ) debug=1       ; shift   ;;
    -- ) shift ; break ;;
esac ; done

################################################################################################ Set Variables

AppName=wine
AppNameLower=wine
Need_SourceCode=no
pm_action=uninstall

if [[ -f /etc/inexistence/00.Installation/function ]]; then
    source /etc/inexistence/00.Installation/function
else
    wget -qO /tmp/function https://github.com/Aniverse/inexistence/raw/master/00.Installation/function
    source /tmp/function
fi

set_variables_log_location

################################################################################################





function uninstall_wine() {

    echo >> $OutputLOG

    if [[ $DISTRO == Ubuntu ]]; then
        apt-add-repository -ry https://dl.winehq.org/wine-builds/ubuntu/ >> $OutputLOG 2>&1
    elif [[ $DISTRO == Debian ]]; then
        rm -f /etc/apt/sources.list.d/wine.list >> $OutputLOG 2>&1
    fi

    apt-get update >> $OutputLOG 2>&1
    apt-get purge -y winehq-stable >> $OutputLOG 2>&1

    status_lock=${AppNameLower}-r
    rm -f /tmp/$status_lock.1.lock /tmp/$status_lock.2.lock $LOCKLocation/$AppNameLower.lock
    which wine > /dev/null && touch /tmp/$status_lock.2.lock || touch /tmp/$status_lock.1.lock
    echo >> $OutputLOG

}





echo -ne "Uninstalling $AppName ..." | tee -a $OutputLOG
uninstall_wine & spinner $!
check_status $status_lock | tee -a $OutputLOG
