#!/bin/bash
#
# https://github.com/Aniverse/inexistence
# Author: Aniverse
#
script_update=2019.08.12
script_version=r20001

torrentid=$1
torrentname=$2
torrentpath=$3

log=/log/script/deluge-update-tracker.log
[[ ! -f $log ]] && { mkdir -p $(dirname $log) ; touch $log ; }

# ddport=58846
ddport=$(grep '"daemon_port": [0-9]*' $HOME/.config/deluge/core.conf | grep -oE "[0-9]+")
[[ -z $ddport ]] && echo "ERROR: No daemon port detected!" >> $log && exit 1
[[ -z $(which deluge-console) ]] && echo "ERROR: No deluge-console detected!" >> $log && exit 1

x=1
while [ $x -le 45 ]; do
    sleep 2
    echo "$(date "+%Y.%m.%d %H:%M:%S"), Running $x times" >> $log
    echo "TorrentID: $torrentid" >> $log
    line=$(deluge-console "connect 127.0.0.1:$ddport; info" $1 | grep "Tracker status")
    echo $line >> $log
    case "$line" in
        *unregistered*|*Sent*|*End*of*file*|*Bad*Gateway*)
            deluge-console "connect 127.0.0.1:$ddport; pause '$torrentid'"
            sleep 2
            deluge-console "connect 127.0.0.1:$ddport; resume '$torrentid'"
            ;;
        *)
            echo "Found working torrent: $torrentname $torrentpath $torrentid" >> $Log
            exit 1;;
    esac
    x=$(( $x + 1 ))
done

#######################################################

unused_codes_ignore_these() {
    Usernamee=ANUSER
    Passwordd=ANPASS
    line=$(/usr/bin/deluge-console "connect 127.0.0.1:$ddport $Usernamee $Passwordd; info" $1 | grep "Tracker status")
    echo $line >> $log
    case "$line" in
        *unregistered*|*Sent*|*End*of*file*|*Bad*Gateway*) eval /usr/bin/deluge-console "connect 127.0.0.1:$ddport $Usernamee $Passwordd\; update-tracker '$torrentid'";;
        *) echo "Found working torrent: $torrentname $torrentpath $torrentid" >> ~/script.log ; exit 1 ;;
    esac
}
